In [15]:
import numpy as np
import quantumstatetomo as qst
import qutip as qt

In [9]:
# H + CNOT

counts_zero = np.array([0.409187, 0.590812, 0.321129, 0.67887, 0.164688, 0.835311])
counts_one =  np.array([0.60398, 0.396019, 0.397557, 0.602442,0.841656, 0.158343])
counts_plus = np.array([0.936076, 0.063923, 0.574012, 0.425987, 0.334107, 0.665892])
counts_imag = np.array([0.634242, 0.365757, 0.15505, 0.844949, 0.325507, 0.674492])

counts_tot = [counts_zero,counts_one,counts_plus,counts_imag]

In [22]:
#

counts_zero_2 = np.array([0.49583, 0.504169, 0.35281, 0.647189, 0.266082, 0.733917])
counts_one_2 = np.array([0.549369, 0.45063, 0.663609, 0.33639, 0.74711, 0.252889])
counts_plus_2 = np.array([1,0, 0.671602, 0.328297, 0.361787, 0.638212])
counts_imag_2 = np.array([0.405441, 0.594558, 0.368493, 0.631506,0.489009, 0.51099])

counts_tot_2 = [counts_zero_2,counts_one_2,counts_plus_2,counts_imag_2]

In [26]:
counts_zero_3 = np.array([0.767911, 0.232088, 0.674457, 0.325542, 0.422445, 0.577554])
counts_one_3 = np.array([1, 0, 0.200244, 0.799755, 0.894938, 0.105061])
counts_plus_3 = np.array([1,0,0.200286, 0.799713,0.516899, 0.4831])
counts_imag_3 = np.array([0.752027, 0.247972, 0.913053, 0.086946, 0.844621, 0.155378])

counts_tot_3 = [counts_zero_3,counts_one_3,counts_plus_3,counts_imag_3]

In [33]:
counts_zero_4 = np.array([0, 1, 0.34958, 0.650419, 0.943377, 0.056622])
counts_one_4 = np.array([0.949644, 0.050355, 0.437943, 0.562056, 0.087649, 0.91235])
counts_plus_4 = np.array([0.112714, 0.88785, 0.362745, 0.637254, 0.25193, 0.748069])
counts_imag_4 = np.array([0.619688,0.380311, 0.000745, 0.999254,0.470386, 0.529613])

counts_tot_4 = [counts_zero_4,counts_one_4,counts_plus_4,counts_imag_4]

In [10]:
measurements = ["H", "V", "D", "A", "L", "R"]

In [11]:
def get_tomoresults(counts, measurements):
    tomo_results = []
    for count in counts:
        print(count)
        tomo_object = qst.QubitTomo(n_qubits)
        rho = tomo_object.qst_MLE(measurements, count)
        tomo_results.append(np.array(rho.matrix))
    return tomo_results

def getchoi(tomoresults):
    zero = tomoresults[0]
    one = tomoresults[1]
    plus = tomoresults[2]
    imag = tomoresults[3]
    
    choi00 = zero
    choi11 = one
    choi01 = plus + 1j * imag -(1+1j)*(zero + one)/2 
    choi10 = plus - 1j * imag -(1-1j)*(zero + one)/2 
    
    choi = np.block([[choi00, choi01], 
                     [choi10, choi11]])
    return choi

In [13]:
n_qubits = 1
tomo_object = qst.QubitTomo(n_qubits)
results = get_tomoresults(counts_tot, measurements)

[0.409187 0.590812 0.321129 0.67887  0.164688 0.835311]
Optimization terminated successfully    (Exit mode 0)
            Current function value: 6.751792183611316e-09
            Iterations: 16
            Function evaluations: 84
            Gradient evaluations: 16
[0.60398  0.396019 0.397557 0.602442 0.841656 0.158343]
Optimization terminated successfully    (Exit mode 0)
            Current function value: 4.1159726857368415e-08
            Iterations: 15
            Function evaluations: 79
            Gradient evaluations: 15
[0.936076 0.063923 0.574012 0.425987 0.334107 0.665892]
Optimization terminated successfully    (Exit mode 0)
            Current function value: 1.4050419744541945e-08
            Iterations: 36
            Function evaluations: 190
            Gradient evaluations: 36
[0.634242 0.365757 0.15505  0.844949 0.325507 0.674492]
Optimization terminated successfully    (Exit mode 0)
            Current function value: 5.429885164592964e-07
            Iterations

In [17]:
qt.Qobj(getchoi(results))

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[ 0.40927308+0.j         -0.17890741+0.33533278j  0.42943005+0.12818434j
   0.03618968-0.0353906j ]
 [-0.17890741-0.33533278j  0.59072692+0.j          0.39282022-0.3737685j
  -0.42943005-0.12818434j]
 [ 0.42943005-0.12818434j  0.39282022+0.3737685j   0.60397944+0.j
  -0.10216977-0.34165837j]
 [ 0.03618968+0.0353906j  -0.42943005+0.12818434j -0.10216977+0.34165837j
   0.39602056+0.j        ]]

In [21]:
np.round(np.linalg.eigvals(getchoi(results)/2),3)

array([ 0.821-0.j, -0.112-0.j,  0.232+0.j,  0.058-0.j])

In [23]:
results_2 = get_tomoresults(counts_tot_2, measurements)

[0.49583  0.504169 0.35281  0.647189 0.266082 0.733917]
Optimization terminated successfully    (Exit mode 0)
            Current function value: 1.2069594707660258e-08
            Iterations: 15
            Function evaluations: 81
            Gradient evaluations: 15
[0.549369 0.45063  0.663609 0.33639  0.74711  0.252889]
Optimization terminated successfully    (Exit mode 0)
            Current function value: 4.073919458302343e-09
            Iterations: 12
            Function evaluations: 64
            Gradient evaluations: 12
[1.       0.       0.671602 0.328297 0.361787 0.638212]
Optimization terminated successfully    (Exit mode 0)
            Current function value: 0.0020668011381706703
            Iterations: 26
            Function evaluations: 135
            Gradient evaluations: 26
[0.405441 0.594558 0.368493 0.631506 0.489009 0.51099 ]
Optimization terminated successfully    (Exit mode 0)
            Current function value: 4.983444685062541e-09
            Iterations:

In [24]:
qt.Qobj(getchoi(results_2))

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[ 0.49578292+0.j         -0.1473205 +0.23387284j  0.43841651-0.11708434j
   0.12492603-0.0122998j ]
 [-0.1473205 -0.23387284j  0.50421708+0.j          0.16026292-0.26694321j
  -0.43841651+0.11708434j]
 [ 0.43841651+0.11708434j  0.16026292+0.26694321j  0.54936795+0.j
   0.16365619-0.24713462j]
 [ 0.12492603+0.0122998j  -0.43841651-0.11708434j  0.16365619+0.24713462j
   0.45063205+0.j        ]]

In [25]:
np.round(np.linalg.eigvals(getchoi(results_2)/2),3)

array([ 0.677-0.j, -0.126-0.j,  0.125+0.j,  0.324+0.j])

In [29]:
results_3 = get_tomoresults(counts_tot_3, measurements)

[0.767911 0.232088 0.674457 0.325542 0.422445 0.577554]
Optimization terminated successfully    (Exit mode 0)
            Current function value: 6.337367644219877e-07
            Iterations: 24
            Function evaluations: 125
            Gradient evaluations: 24
[1.       0.       0.200244 0.799755 0.894938 0.105061]
Optimization terminated successfully    (Exit mode 0)
            Current function value: 0.024914302995708137
            Iterations: 16
            Function evaluations: 85
            Gradient evaluations: 16
[1.       0.       0.200286 0.799713 0.516899 0.4831  ]
Optimization terminated successfully    (Exit mode 0)
            Current function value: 0.005336115572628766
            Iterations: 30
            Function evaluations: 155
            Gradient evaluations: 30
[0.752027 0.247972 0.913053 0.086946 0.844621 0.155378]
Optimization terminated successfully    (Exit mode 0)
            Current function value: 0.005340243566526313
            Iterations: 16

In [30]:
qt.Qobj(getchoi(results_3))

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[ 0.76813333+0.j          0.17451299+0.0765839j   0.12010891-0.10333113j
  -0.04507618+0.45655151j]
 [ 0.17451299-0.0765839j   0.23186667+0.j         -0.41941778+0.28038631j
  -0.12010891+0.10333113j]
 [ 0.12010891+0.10333113j -0.41941778-0.28038631j  0.85699162+0.j
  -0.21046997-0.27974853j]
 [-0.04507618-0.45655151j -0.12010891-0.10333113j -0.21046997+0.27974853j
   0.14300838+0.j        ]]

In [31]:
np.round(np.linalg.eigvals(getchoi(results_3)/2),3)

array([ 0.648-0.j,  0.476+0.j, -0.19 +0.j,  0.067-0.j])

In [34]:
results_4 = get_tomoresults(counts_tot_4, measurements)

[0.       1.       0.34958  0.650419 0.943377 0.056622]
Optimization terminated successfully    (Exit mode 0)
            Current function value: 0.021567684217954432
            Iterations: 8
            Function evaluations: 43
            Gradient evaluations: 8
[0.949644 0.050355 0.437943 0.562056 0.087649 0.91235 ]
Optimization terminated successfully    (Exit mode 0)
            Current function value: 0.008342490934675834
            Iterations: 22
            Function evaluations: 117
            Gradient evaluations: 22
[0.112714 0.88785  0.362745 0.637254 0.25193  0.748069]
Optimization terminated successfully    (Exit mode 0)
            Current function value: 1.6421296469983142e-07
            Iterations: 23
            Function evaluations: 120
            Gradient evaluations: 23
[6.19688e-01 3.80311e-01 7.45000e-04 9.99254e-01 4.70386e-01 5.29613e-01]
Optimization terminated successfully    (Exit mode 0)
            Current function value: 0.00032238154508279363
       

In [36]:
qt.Qobj(getchoi(results_4))

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[ 0.13418405+0.j         -0.10705277-0.32360188j -0.38811943+0.11081968j
  -0.08074699-0.16660795j]
 [-0.10705277+0.32360188j  0.86581595+0.j         -0.03729033-0.65060232j
   0.38811943-0.11081968j]
 [-0.38811943-0.11081968j -0.03729033+0.65060232j  0.86770549+0.j
  -0.04887338+0.33526687j]
 [-0.08074699+0.16660795j  0.38811943+0.11081968j -0.04887338-0.33526687j
   0.13229451+0.j        ]]

In [35]:
np.round(np.linalg.eigvals(getchoi(results_4)/2),3)

array([ 0.934+0.j,  0.129-0.j, -0.015+0.j, -0.049+0.j])