In [1]:
import warnings
warnings.filterwarnings("ignore")

This is an old library I made to perform quantum state tomography. Since I made the library to be applicable to quantum optics, the measurements are in terms of polarization. You can still apply it in standard notation for quantum states:

$Z$ basis
$|H\rangle = |0\rangle$
$|V\rangle = |1\rangle$

$X$ basis
$|+\rangle = |D\rangle$
$|-\rangle = |A\rangle$

$Y$ basis
$|+i\rangle = |L\rangle$
$|-i\rangle = |R\rangle$

In [2]:
import quantumstatetomo as qst
import numpy as np
import qutip as qt

Initialize the quantum state tomography object. Here we use 1 qubit:

In [3]:
n_qubits = 1
tomo_object = qst.QubitTomo(n_qubits)

We have to define which measurements were done. See the above comment to convert to the usual notation.

In [4]:
measurements = ["H", "V", "D", "A", "L", "R"]

Input the corresponding data for each of the measurement results

# Tomography on input state $|0\rangle$

In [5]:
counts_groud = np.array([1, 0, 0.5, 0.5, 0.5, 0.5])
groundstate = tomo_object.qst_MLE(measurements, counts_groud)
qt.Qobj(groundstate.matrix)

Optimization terminated successfully    (Exit mode 0)
            Current function value: 3.178095417401875e-09
            Iterations: 7
            Function evaluations: 38
            Gradient evaluations: 7


Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[9.99999995e-01+0.00000000e+00j 4.86407046e-05-3.65546458e-05j]
 [4.86407046e-05+3.65546458e-05j 4.84643138e-09+0.00000000e+00j]]

Now, we can do the same process on each state of interest:

# Data

In [6]:
# ideal identity
counts_zero_id = np.array([1, 0, 1/2, 1/2, 1/2, 1/2])
counts_one_id =  np.array([0, 1, 1/2, 1/2, 1/2, 1/2])
counts_plus_id = np.array([1/2, 1/2, 1, 0, 1/2, 1/2])
counts_imag_id = np.array([1/2, 1/2, 1/2, 1/2, 1, 0])

counts_tot_id = [counts_zero_id,counts_one_id,counts_plus_id,counts_imag_id]

In [7]:
# ideal Z
counts_zero_Z = np.array([1, 0, 1/2, 1/2, 1/2, 1/2])
counts_one_Z =  np.array([0, 1, 1/2, 1/2, 1/2, 1/2])
counts_plus_Z = np.array([1/2, 1/2, 0, 1, 1/2, 1/2])
counts_imag_Z = np.array([1/2, 1/2, 1/2, 1/2, 0, 1])

counts_tot_Z = [counts_zero_Z,counts_one_Z,counts_plus_Z,counts_imag_Z]

In [8]:
# ideal X
counts_zero_X = np.array([0, 1, 1/2, 1/2, 1/2, 1/2])
counts_one_X = np.array([1, 0, 1/2, 1/2, 1/2, 1/2])
counts_plus_X = np.array([1/2, 1/2, 1, 0, 1/2, 1/2])
counts_imag_X = np.array([1/2, 1/2, 1/2, 1/2, 0, 1])

counts_tot_X = [counts_zero_X,counts_one_X,counts_plus_X,counts_imag_X]

In [9]:
# ideal Sqrt X
counts_zero_SqrtX = np.array([1/2,1/2, 1/2, 1/2, 0, 1])
counts_one_SqrtX =  np.array([1/2, 1/2, 1/2, 1/2, 1,0])
counts_plus_SqrtX = np.array([1/2, 1/2, 1, 0, 1/2, 1/2])
counts_imag_SqrtX = np.array([1, 0, 1/2, 1/2, 1/2, 1/2])

counts_tot_SqrtX = [counts_zero_SqrtX,counts_one_SqrtX,counts_plus_SqrtX,counts_imag_SqrtX]

In [10]:
# gate: Z
counts_zero_real = np.array([1,0,0.5,0.5, 0.675088, 0.324911])
counts_one_real = np.array([0, 0.992678, 0.595311, 0.505688, 0.325639, 0.67436])
counts_plus_real = np.array([0.5, 0.5, 0,1, 0.5, 0.5])
counts_imag_real=np.array([0.711812, 0.288187, 0.778007, 0.221992, 0, 1])

counts_zero_Zreal=np.array([1,0, 0.590612, 0.409387, 0.585846, 0.415153])
counts_one_Zreal =np.array([0.007163, 0.992836, 0.5, 0.5,0.482062,0.517937])
counts_plus_Zreal = np.array([0.5,0.5,0,1,0.756525,0.243474])
counts_imag_Zreal = np.array([0.294445, 0.705554, 0.729905, 0.270094, 0, 1])

counts_tot_real=[counts_zero_Zreal,counts_one_Zreal,counts_plus_Zreal,counts_imag_Zreal]

In [11]:
# gate: X
counts_zero_real2=np.array([0,1, 0.392822,0.606177, 0.657176, 0.342823])
counts_one_real2=np.array([1,0, 0.5,0.5,0.438488, 0.561511])
counts_plus_real2 = np.array([0.5, 0.5, 0.014501, 0.985498, 0.552788, 0.447211])
counts_imag_real2 = np.array([0.702849, 0.29715, 0.745083, 0.254916, 0.995911, 0.004088])

counts_zero_Xreal2=np.array([0, 1, 0.5, 0.5, 0.5, 0.5])
counts_one_Xreal2=np.array([1, 0, 0.5, 0.5, 0.5, 0.5])
counts_plus_Xreal2 = np.array([0.5, 0.5, 1,0, 0.627134, 0.372865])
counts_imag_Xreal2 = np.array([0.277033, 0.722966, 0.72134, 0.278569, 0, 1])


counts_tot_Xreal2=[counts_zero_Xreal2,counts_one_Xreal2,counts_plus_Xreal2,counts_imag_Xreal2]

In [12]:
 # SQRT X (redo)
counts_zero_SqrtXreal = np.array([0.304315, 0.695684, 0.793958, 0.206041, 0, 1])
counts_one_SqrtXreal = np.array([0.748577, 0.251422, 0.281981, 0.718018, 1,0])
counts_plus_SqrtXreal = np.array([0.5, 0.5,1,0,0.74518, 0.254981])
counts_imag_SqrtXreal = np.array([1,0,0.5,0.5,0.5, 0.5])

counts_tot_SqrtX_real = [counts_zero_SqrtXreal, counts_one_SqrtXreal, counts_plus_SqrtXreal, counts_imag_SqrtXreal]

In [13]:
# gate: Sqrt Y
counts_zero_SqrtYreal= np.array([0.5, 0.5, 1,0, 0.632044, 0.367955])
counts_one_SqrtYreal = np.array([0.5, 0.5, 0,1, 0.185172, 0.814827])
counts_plus_SqrtYreal =np.array([0,1, 0.5, 0.5,0.5, 0.5])
counts_imag_SqrtYreal=np.array([0, 1, 0.24758, 0.752419, 1,0])

counts_tot_SqrtYreal = [counts_zero_SqrtYreal,counts_one_SqrtYreal,counts_plus_SqrtYreal,counts_imag_SqrtYreal]

In [20]:
# gate: Id (no process)

counts_zero_idreal = np.array([1,0, 0.5, 0.5, 0.5, 0.5])
counts_one_idreal =  np.array([0,1,0.5, 0.5, 0.5, 0.5])
counts_plus_idreal = np.array([0.5, 0.5, 1,0, 0.694413, 0.305586])
counts_imag_idreal = np.array([0.705312, 0.294687, 0.229734, 0.770265, 1,0])

counts_tot_idreal = [counts_zero_idreal,counts_one_idreal,counts_plus_idreal,counts_imag_idreal]

In [15]:
def get_tomoresults(counts, measurements):
    tomo_results = []
    for count in counts:
        print(count)
        tomo_object = qst.QubitTomo(n_qubits)
        rho = tomo_object.qst_MLE(measurements, count)
        tomo_results.append(np.array(rho.matrix))
    return tomo_results

Now, we have reconstructed $\mathcal{E}|0\rangle\langle 0|,\space \mathcal{E}|1\rangle\langle 1|, \space\mathcal{E}|+\rangle\langle +|,\space \mathcal{E}|i\rangle\langle i|$ .

To get $\mathcal{E}|0\rangle\langle 1|$, $\mathcal{E}|1\rangle\langle 0|$, we do:

$\mathcal{E}|0\rangle\langle 1|$ = $\mathcal{E}|+\rangle\langle +| + i\mathcal{E}|i\rangle\langle i| - \dfrac{1+i}{2}\Big(\mathcal{E}|0\rangle\langle 0|+\mathcal{E}|1\rangle\langle 1|\Big)$

$\mathcal{E}|1\rangle\langle 0|$ = $\mathcal{E}|+\rangle\langle +| - i\mathcal{E}|i\rangle\langle i| - \dfrac{1-i}{2}\Big(\mathcal{E}|0\rangle\langle 0|+\mathcal{E}|1\rangle\langle 1|\Big)$

In [16]:
def getchoi(tomoresults):
    zero = tomoresults[0]
    one = tomoresults[1]
    plus = tomoresults[2]
    imag = tomoresults[3]
    
    choi00 = zero
    choi11 = one
    choi01 = plus + 1j * imag -(1+1j)*(zero + one)/2 
    choi10 = plus - 1j * imag -(1-1j)*(zero + one)/2 
    
    choi = np.block([[choi00, choi01], 
                     [choi10, choi11]])
    return choi

# Identity (Ideal)

In [17]:
results_id = get_tomoresults(counts_tot_id, measurements)

[1.  0.  0.5 0.5 0.5 0.5]
Optimization terminated successfully    (Exit mode 0)
            Current function value: 3.178095417401875e-09
            Iterations: 7
            Function evaluations: 38
            Gradient evaluations: 7
[0.  1.  0.5 0.5 0.5 0.5]
Optimization terminated successfully    (Exit mode 0)
            Current function value: 3.2411893549180394e-06
            Iterations: 9
            Function evaluations: 48
            Gradient evaluations: 9
[0.5 0.5 1.  0.  0.5 0.5]
Optimization terminated successfully    (Exit mode 0)
            Current function value: 4.0683414475116035e-07
            Iterations: 19
            Function evaluations: 100
            Gradient evaluations: 19
[0.5 0.5 0.5 0.5 1.  0. ]
Optimization terminated successfully    (Exit mode 0)
            Current function value: 2.5428438449672457e-07
            Iterations: 20
            Function evaluations: 106
            Gradient evaluations: 20


In [18]:
tomo_object.display_rho(np.round(getchoi(results_id),4))

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[ 1.000e+00+0.j      0.000e+00+0.j     -2.000e-04-0.0002j
   9.994e-01-0.0005j]
 [ 0.000e+00+0.j      0.000e+00+0.j     -4.000e-04-0.0002j
   2.000e-04+0.0002j]
 [-2.000e-04+0.0002j -4.000e-04+0.0002j  6.000e-04+0.j
   7.000e-04+0.0001j]
 [ 9.994e-01+0.0005j  2.000e-04-0.0002j  7.000e-04-0.0001j
   9.994e-01+0.j    ]]

# Identity (real data)

In [21]:
results_idreal = get_tomoresults(counts_tot_idreal, measurements)

[1.  0.  0.5 0.5 0.5 0.5]
Optimization terminated successfully    (Exit mode 0)
            Current function value: 3.178095417401875e-09
            Iterations: 7
            Function evaluations: 38
            Gradient evaluations: 7
[0.  1.  0.5 0.5 0.5 0.5]
Optimization terminated successfully    (Exit mode 0)
            Current function value: 3.2411893549180394e-06
            Iterations: 9
            Function evaluations: 48
            Gradient evaluations: 9
[0.5      0.5      1.       0.       0.694413 0.305586]
Optimization terminated successfully    (Exit mode 0)
            Current function value: 0.0014097718845429946
            Iterations: 18
            Function evaluations: 94
            Gradient evaluations: 18
[0.705312 0.294687 0.229734 0.770265 1.       0.      ]
Optimization terminated successfully    (Exit mode 0)
            Current function value: 0.007670745126239751
            Iterations: 13
            Function evaluations: 69
            Gradient eval

In [22]:
tomo_object.display_rho(np.round(getchoi(results_idreal),4))

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[ 1.000e+00+0.000e+00j  0.000e+00+0.000e+00j -1.000e-04+1.645e-01j
   8.874e-01-3.919e-01j]
 [ 0.000e+00+0.000e+00j  0.000e+00+0.000e+00j  4.940e-02-4.400e-02j
   1.000e-04-1.645e-01j]
 [-1.000e-04-1.645e-01j  4.940e-02+4.400e-02j  6.000e-04+0.000e+00j
   7.000e-04+1.000e-04j]
 [ 8.874e-01+3.919e-01j  1.000e-04+1.645e-01j  7.000e-04-1.000e-04j
   9.994e-01+0.000e+00j]]

# Z Gate (ideal)

In [ ]:
results_Z = get_tomoresults(counts_tot_Z, measurements)

In [ ]:
tomo_object.display_rho(getchoi(np.round(results_Z, 2)))

# Z Gate (Experiment)

In [ ]:
results_Z_real = get_tomoresults(counts_tot_real, measurements)

In [ ]:
tomo_object.display_rho(getchoi(np.round(results_Z_real,3)))

In [ ]:
np.linalg.eigvals(getchoi(results_Z_real)/2)

# $\sqrt{X}$ Gate (Ideal)

In [ ]:
results_SqrtX = get_tomoresults(counts_tot_SqrtX, measurements)

In [ ]:
tomo_object.display_rho(getchoi(np.round(results_SqrtX, 2)))

# $\sqrt{X}$ Gate (Experiment)

In [ ]:
results_SqrtX_real = get_tomoresults(counts_tot_SqrtX_real, measurements)

In [ ]:
tomo_object.display_rho(getchoi(np.round(results_SqrtX_real, 2)))

In [ ]:
np.linalg.eigvals(getchoi(results_SqrtX_real)/2)

# X Gate (Ideal)

In [ ]:
results_X = get_tomoresults(counts_tot_X, measurements)

In [ ]:
tomo_object.display_rho(getchoi(np.round(results_X, 2)))

In [ ]:
np.linalg.eigvals(getchoi(results_X)/2)

# X Gate (Experiment)

In [ ]:
results_realX = get_tomoresults(counts_tot_Xreal2, measurements)

In [ ]:
tomo_object.display_rho(getchoi(np.round(results_realX, 3)))

In [ ]:
np.linalg.eigvals(getchoi(results_realX)/2)

# Fidelity of choi matricies (using diamond norm)

In [ ]:
from qutip.metrics import dnorm

In [ ]:
import forest.benchmarking.distance_measures as dm
from forest.benchmarking.operator_tools import superoperator_transformations

### Average gate fidelity
We have several methods for measuring the fidelity of the reconstucted gates. One of which is the average gate fidelity, provided by the following formula (based on https://arxiv.org/pdf/quant-ph/9807091.pdf)

$$\bar{\mathcal{F}_{\mathcal{E}}} = \dfrac{n + \sum_i |\text{Tr}(E_i)|^2}{n(n+1)}$$

Where $\{E_i\}$ are the Kraus operators of $\mathcal{E}$, $n$ is the dimension of the system.

In [ ]:
def avggatefidelity(choi, n):
    kraus = superoperator_transformations.choi2kraus(choi)
    summ = 0
    for E in kraus:
        summ += np.abs(np.trace(E)) ** 2
    
    return (n + summ)/(n * (n+1))

### Diamond Distance

We can also use the diamond distance, which is used to determine the **distinguishability** of two quantum channels:

$$d_{\diamond}(\mathcal{E}, \mathcal{F}) = \text{max}_{\rho} ||(\mathcal{E}\otimes1)\rho -(\mathcal{F}\otimes1)\rho||_1 \leq1$$

### Fidelity of Chi (process) matricies

If we convert the reconstructed choi matrix into Chi (process) matricies, we can use the following measure of fidelity:

$$\mathcal{F}(\chi_{th}, \chi_{exp}) = \dfrac{\text{Tr} (\chi_{exp}\chi_{th}^{\dagger})}{\sqrt{\text{Tr}\chi_{th}^{\dagger}\chi_{th} }\sqrt{\text{Tr}\chi_{exp}^{\dagger}\chi_{exp}}}$$

In [ ]:
def fidelitychi(th_choi, exp_choi):
    th = superoperator_transformations.choi2chi(th_choi)
    exp = superoperator_transformations.choi2chi(exp_choi)
    
    return np.trace(exp * th.conj().T)/(np.sqrt(np.trace(th.conj().T*th))*np.sqrt(np.trace(exp.conj().T*exp)))

### X Gate

In [ ]:
xgateidealchoi = np.array([[0,0,0,0],
                       [0,1,1,0],
                       [0,1,1,0],
                       [0,0,0,0]])


In [ ]:
fidelitychi(xgateidealchoi, getchoi(results_realX))

In [ ]:
dm.diamond_norm_distance(xgateidealchoi, getchoi(results_realX))

### $\sqrt{X}$ gate

In [ ]:
sqrtxgateideal = np.array([[0.5,  0.5j,0.5j, 0.5],
                       [-0.5j,0.5, 0.5, -0.5j],
                       [-0.5j,0.5, 0.5, -0.5j],
                       [0.5,  0.5j,0.5j, 0.5]])

In [ ]:
fidelitychi(sqrtxgateideal, getchoi(results_SqrtX_real))

In [ ]:
dm.diamond_norm_distance(sqrtxgateideal, getchoi(results_SqrtX_real))

### $Z$ gate

In [ ]:
zgateideal=np.array([[1,0,0,-1],
                    [0,0,0,0],
                    [0,0,0,0],
                    [-1,0,0,1]])

In [ ]:
fidelitychi(zgateideal, getchoi(results_Z_real))

In [ ]:
dm.diamond_norm_distance(zgateideal, getchoi(results_Z_real))

# Eigenvalues

### Z Gate

In [ ]:
np.linalg.eigvals(getchoi(results_Z_real)/2)

### X Gate

In [ ]:
np.linalg.eigvals(getchoi(results_realX)/2)

### $\sqrt{X}$ Gate

In [ ]:
np.linalg.eigvals(getchoi(results_SqrtX_real)/2)

### Identity gate

In [23]:
np.linalg.eigvals(getchoi(results_idreal)/2)

array([ 0.99179658-3.46325463e-17j, -0.0885197 -3.54949746e-17j,
        0.08897736-8.45309665e-18j,  0.00774576+7.45695504e-18j])

# Kraus Ops

In [ ]:
def print_kraus(superop):
    kraus_ops = superoperator_transformations.choi2kraus(getchoi(np.round(superop,2))/2)
    for op in kraus_ops:
        print(op)

### Z Gate

In [ ]:
# ideal gate
print_kraus(results_Z)

In [ ]:
# real gate
print_kraus(results_Z_real)

### X gate

In [ ]:
# ideal gate
print_kraus(results_X)

In [ ]:
# real gate
print_kraus(results_realX)

### $\sqrt{X}$ Gate

In [ ]:
# ideal gate
print_kraus(results_SqrtX)

In [ ]:
# real gate
print_kraus(results_SqrtX_real)

## Noise Analysis

In this section, we try to characterize the noise for each reconstructed gate. In particular, we are interested in seeing how similar the noise is between each gate. 

In general, a reconstructed gate, $\bar{U}$ can be decomposed in terms of the ideal gate $U$ and the noise in the machine, $N_U$:

<img src="diagrams/reconstructed_gate.png" width="400">.

Using the superator representation, we have

$$ S(N_U \circ U ) = S(N_U) \cdot S(U) = S(\bar{U})$$

Hence

$$ S(N_U)  = S(\bar{U}) \cdot S^{-1}(U).$$

We find $N_U$ for the gates we previously reconstructed:

## Z Gate

In [ ]:
superopZ_reconstructed = superoperator_transformations.choi2superop(getchoi(results_Z))
superopZ = superoperator_transformations.choi2superop(zgateideal)
superopZ_inv = np.linalg.inv(superopZ)

In [ ]:
noise_Z = np.matmul(superopZ_reconstructed, superopZ_inv)

As a superoperator

In [ ]:
qt.Qobj(np.round(noise_Z,3))

As a Choi matrix (unnormalizaed)

In [ ]:
qt.Qobj(np.round(superoperator_transformations.superop2choi(noise_Z),3))

## X Gate

In [ ]:
superopX_reconstructed = superoperator_transformations.choi2superop(getchoi(results_X))
superopX = superoperator_transformations.choi2superop(xgateidealchoi)
superopX_inv = np.linalg.inv(superopX)

In [ ]:
noise_X = np.matmul(superopX_reconstructed, superopX_inv)

In [ ]:
qt.Qobj(np.round(noise_X,3))

In [ ]:
qt.Qobj(np.round(superoperator_transformations.superop2choi(noise_X),3))

## $\sqrt{X}$ Gate

In [ ]:
superopSqrtX_reconstructed = superoperator_transformations.choi2superop(getchoi(results_SqrtX))
superopSqrtX = superoperator_transformations.choi2superop(sqrtxgateideal)
superopSqrtX_inv = np.linalg.inv(superopSqrtX)

In [ ]:
noise_SqrtX = np.matmul(superopSqrtX_reconstructed, superopSqrtX_inv)

In [ ]:
qt.Qobj(np.round(noise_SqrtX,3))

In [ ]:
qt.Qobj(np.round(superoperator_transformations.superop2choi(noise_SqrtX),3))